name: Build & Push Cloudshell Images

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner}}
        password: ${{ secrets.GHCR_BUILD_PUSH_TOKEN }}

    - name: Generate Tag
      id: tag
      run: |
        echo "image_tag=${{ github.sha }}-$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Base image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: linux/base.Dockerfile
        push: true
        tags: ghcr.io/kkamegawa/cloudshell/base:${{ steps.tag.outputs.image_tag }},ghcr.io/kkamegawa/cloudshell/base:latest
        platforms: linux/amd64,linux/arm64

    - name: Tools image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: linux/tools.Dockerfile
        push: true
        tags: ghcr.io/kkamegawa/cloudshell/:${{ steps.tag.outputs.image_tag }},ghcr.io/kkamegawa/cloudshell:latest
        build-args: IMAGE_LOCATION=ghcr.io/cloudshell/base:${{ steps.tag.outputs.image_tag  }}
        platforms: linux/amd64,linux/arm64
